#!/bin/sh
if [ $# -eq 0 ]; then set all install; fi  # "$@" breaks make for empty args
/usr/bin/make CC="lcc -A" XCFLAGS=-DTEMPNAM BIN=/usr/local/bin LIB2=/usr/local/noweb/lib LIB3=/usr/local/lib/noweb3 MAN=/usr/local/man TEXINPUTS=/usr/share/texmf/tex/latex/local ELISP=$HOME/emacs "$@"
