# makefile for lua hierarchy

include ../nwconfig

all:
	cd src
	$(MK) -f Makefile.win all
	cd ..
	cd clients/lib
	$(MK) -f Makefile.win all
	cd ../..

clean:
	cd src
	$(MK) -f Makefile.win clean
	cd ..
	cd clients/lib
	$(MK) -f Makefile.win clean
	cd ../..

install:
	cd src/luac; make all
	cd clients/lua; make all

old:
	cd clients/lib/old; make $@

clobber: clean
	cd src
	$(MK) -f Makefile.win clobber
	cd ..
	cd clients/lib
	$(MK) -f Makefile.win clobber
	cd ../..
