# makefile for lua hierarchy

include ../nwconfig

all:
	cd src
	$(MK) -f Makefile.win all
	cd ..
	cd clients/lib
	$(MK) -f Makefile.win all
	cd ../..

co clean klean:
	cd include; make $@
	cd src; make $@
	cd src/luac; make $@
	cd clients/lib; make $@
	cd clients/lib/old; make $@
	cd clients/lua; make $@

install:
	cd src/luac; make all
	cd clients/lua; make all

old:
	cd clients/lib/old; make $@

clobber: clean
